// old/src/components/advantages.vue
<template>

	<section class="block block--green advantages">
				
		<div class="block__content">

			<h2 class="title">Только у нас:</h2>

			<ul class="advantages-list">
				<li class="advantages__item" v-for="item in items">
					<div :class="['advantages__item-icon', item.class || '']">
						<img :src="urlPrefix + item.icon" v-if="!item.class"/>
						<span v-else>{{item.content}}</span>
					</div>
					<div class="advantages-item__title">
						{{ item.title }}
					</div>
				</li>
			</ul>

		</div>

	</section>

</template>

<script>
	
	export default {

		data(){
			return {

				urlPrefix : 'assets/i/icons/',

				items : [
					{
						title : 'Работаем по всей Архангельской области',
						icon : 'advantages/1.png'
						// class: 'advantages-item__icon_type_letter',
						// content: 'A'
					},
					{
						title : 'Лучшие цены на полотна Германии',
						icon : 'advantages/4.png'
					},
					{
						title : 'Изготовление от одного дня',
						icon : 'advantages/12.png'
					},
					{
						title : 'Бесплатный выезд замерщика',
						icon : 'advantages/10.png'
					},
					{
						title : 'Пенсионерам цены ещё лучше',
						icon : 'advantages/2.png'
					},
					{
						title : 'Гарантия на потолок 15 лет',
						icon : 'advantages/5.png'
					},
					{
						title : 'Только качественные материалы',
						icon : 'advantages/11.png'
					},
					{
						title : 'Опытные монтажники',
						icon : 'advantages/9.png'
					},
					{
						title : 'Новоселам скидки',
						icon : 'advantages/3.png'
					},
					{
						title : 'Рассрочка 0%',
						icon : 'advantages/6.png'
					},
					{
						title : 'Печать картин на ткани',
						icon : 'advantages/7.png'
					},
					{
						title : 'Работаем с кор­по­ра­тив­ны­ми клиентами',
						icon : 'advantages/8.png'
					}
				] 
			}
		}

	}

</script>

// src/widgets/Advantages/index.tsx
import { ComponentProps } from 'react';
import Image from 'next/image';
import { Card } from '../../components/Card';
import { List } from '../../components/List';
import { Section } from '../../components/Section';
import { Title } from '../../components/Text';

import IconRegion from './images/1.png';
import IconPresent from './images/2.png';
import IconBuilding from './images/3.png';
import IconCurrency from './images/4.png';
import IconCheckList from './images/5.png';
import IconZeroProcent from './images/6.png';
import IconCamera from './images/7.png';
import IconHandshake from './images/8.png';
import IconTools from './images/9.png';
import IconFree from './images/10.png';
import IconThumbUp from './images/11.png';
import IconSandClock from './images/12.png';


const ListItem = (props: {
    icon: ComponentProps<typeof Image>['src'],
    text: string,
}) => (
    <Card>
        <Image src={props.icon} alt="" width={64} height={64} />
        <div>{props.text}</div>
    </Card>
);


export const Advantages = () => (
    <Section id="advantages" style={{ background: '#f7a136' }}>
        <Title>Только у нас:</Title>
        <List align="center">
            <ListItem icon={IconRegion} text="Работаем по всей Архангельской области" />
            <ListItem icon={IconCurrency} text="Лучшие цены на полотна Германии" />
            <ListItem icon={IconSandClock} text="Изготовление от одного дня" />
            <ListItem icon={IconFree} text="Бесплатный выезд замерщика" />
            <ListItem icon={IconPresent} text="Пенсионерам цены ещё лучше" />
            <ListItem icon={IconCheckList} text="Гарантия на потолок 15 лет" />
            <ListItem icon={IconThumbUp} text="Только качественные материалы" />
            <ListItem icon={IconTools} text="Опытные монтажники" />
            <ListItem icon={IconBuilding} text="Новоселам скидки" />
            <ListItem icon={IconZeroProcent} text="Рассрочка 0%" />
            <ListItem icon={IconCamera} text="Печать картин на ткани" />
            <ListItem icon={IconHandshake} text="Работаем с кор­по­ра­тив­ны­ми клиентами" />
        </List>
    </Section>
);
