// old/src/components/footer.vue
<template>
	
	<section class="block contacts">

		<div class="block__content">

			<div class="contacts__address address">
				<p class="address__title">АрхПотолки</p>
				<p class="address__place">город Архангельск, ул. Беломорской флотилии 2-3-33</p>
				<p class="address__phone">+7 8182 47-67-24</p>
			</div>

			<p><a target="_blank" href="http://vk.com/arhpotolki">vk.com/arhpotolki</a></p>
			<p><a target="_blank" href="mailto:hello@arhpotolki.info">hello@arhpotolki.info</a></p>

			<div class="contacts__vk-widget" id="vk_groups"></div>

			<div 
				class="yashare-auto-init" 
				data-yashareL10n="ru" 
				data-yashareType="small" 
				data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir" 
				data-yashareTheme="counter">
			</div>

			<p class="contacts__copyright">Copyright &copy; АрхПотолки, 2014 - {{ currentYear }} | <a href="/terms.html">Зашита персональной информации</a></p>

		</div>

	</section>
	
</template>

<script>
	
	export default {
		computed : {
			currentYear(){ 
				return (new Date()).getFullYear() 
			}
		},

		methods: {
			initVKWidget(){
				VK.Widgets.Group("vk_groups", {
					mode: 3, 
					color3: 'F7A136'
				}, 53659209)
			}
		},

		mounted() {
			const script = document.createElement('script')
			script.src = '//vk.com/js/api/openapi.js?145'
			script.onload = this.initVKWidget
			this.$el.append(script)
		}
	}

</script>

// src/modules/Footer/index.tsx
import React from "react";
import styles from "./styles.module.css";

function Footer() {
  return (
    <section id="footer">
      <div className={`${styles.contacts} layout`}>
        <div className={styles.address}>
          <p className={styles.address__title}>АрхПотолки</p>{" "}
          <p className="address__place">
            город Архангельск, ул. Беломорской флотилии 2-3-33
          </p>{" "}
          <p className="address__phone">+7 8182 47-67-24</p>
        </div>{" "}
        <p>
          <a target="_blank" href="http://vk.com/arhpotolki">
            vk.com/arhpotolki
          </a>
        </p>{" "}
        <p>
          <a target="_blank" href="mailto:hello@arhpotolki.info">
            hello@arhpotolki.info
          </a>
        </p>{" "}
        <div id="vk_groups" className="contacts__vk-widget"></div>{" "}
        <div
          data-yasharel10n="ru"
          data-yasharetype="small"
          data-yasharequickservices="vkontakte,facebook,twitter,odnoklassniki,moimir"
          data-yasharetheme="counter"
          className="yashare-auto-init"
        ></div>{" "}
        <p className={styles.contacts__copyright}>
          Copyright © АрхПотолки, 2014 - 2023 |{" "}
          <a href="/terms.html">Зашита персональной информации</a>
        </p>
      </div>
    </section>
  );
}

export default Footer;
